include /etc/openldap/schema/core.schema
include /etc/openldap/schema/cosine.schema
include /etc/openldap/schema/inetorgperson.schema

modulepath /usr/lib/openldap
moduleload back_mdb.so

pidfile /run/openldap/slapd.pid
argsfile /run/openldap/slapd.args

database mdb
suffix "dc=company,dc=local"
rootdn "cn=admin,dc=company,dc=local"
rootpw "adminpassword"
directory /var/lib/openldap/openldap-data

maxsize 1073741824

index objectClass eq
index cn,uid,mail eq
