{{- if .Values.kerberos.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yarn-explorer.fullname" . }}-krb5
  labels:
    {{- include "yarn-explorer.labels" . | nindent 4 }}
data:
  krb5.conf: |
    {{- .Values.kerberos.krb5Config | nindent 4 }}
{{- end }}
