{{- if and .Values.kerberos.enabled .Values.kerberos.keytab.keytabBase64 (not .Values.kerberos.keytab.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yarn-explorer.keytabSecretName" . }}
  labels:
    {{- include "yarn-explorer.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.kerberos.keytab.fileName }}: {{ .Values.kerberos.keytab.keytabBase64 }}
{{- end }}
