apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yarn-explorer.fullname" . }}-secrets
  labels:
    {{- include "yarn-explorer.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ (.Values.secrets.jwtSecret | default "yarn-explorer-super-secret-key-change-in-production-random-hash") | b64enc | quote }}
  ldap-password: {{ (.Values.secrets.ldapBindPassword | default "") | b64enc | quote }}
  {{- if .Values.secrets.databasePassword }}
  database-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  {{- end }}
  {{- if and .Values.kerberos.enabled .Values.kerberos.keytab.keytabBase64 }}
  {{ .Values.kerberos.keytab.fileName | default "yarn-explorer.keytab" }}: {{ .Values.kerberos.keytab.keytabBase64 | quote }}
  {{- end }}
