import logging
from typing import List, Dict, Optional
from datetime import datetime, timezone
from collections import defaultdict
from xml.sax.saxutils import escape

from app.models.yarn import QueueDraftItem
from app.models.cluster import ClusterConfig

logger = logging.getLogger(__name__)


def generate_capacity_scheduler_xml(
    queues: List[QueueDraftItem],
    cluster: ClusterConfig,
    generated_by: str = "system",
    comment: str = "",
    resource_mode: Optional[str] = None,
) -> str:
    """
    Генерирует capacity-scheduler.xml из списка QueueDraftItem.
    Поддерживает процентный и абсолютный режимы ресурсов ([memory=...,vcores=...]).
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    mode = resource_mode or cluster.resource_mode

    # Индексируем очереди по пути и строим дерево
    queue_map: Dict[str, QueueDraftItem] = {}
    for q in queues:
        if q.action != "delete":
            queue_map[q.path] = q

    # Группируем детей по parent_path
    children_by_parent: Dict[str, List[str]] = defaultdict(list)
    for q in queues:
        if q.action != "delete" and q.parent_path:
            children_by_parent[q.parent_path].append(q.name)

    properties: List[tuple] = []

    def add_prop(name: str, value: str, description: str = ""):
        properties.append((name, value, description))

    # Основные свойства
    add_prop(
        "yarn.scheduler.capacity.maximum-applications",
        "10000",
        "Maximum number of applications in the system"
    )

    total_mem = cluster.total_resources.memory_mb
    total_cores = cluster.total_resources.vcores

    # Обрабатываем каждую очередь
    sorted_paths = sorted(queue_map.keys())
    for path in sorted_paths:
        q = queue_map[path]
        prop_prefix = f"yarn.scheduler.capacity.{path}"

        # Список дочерних очередей
        if path in children_by_parent:
            child_names = ",".join(sorted(children_by_parent[path]))
            add_prop(f"{prop_prefix}.queues", child_names)

        # Для каждой партиции
        for part_name, part_config in q.partitions.items():
            if mode == "absolute" and path != "root":
                mem = part_config.memory_mb if part_config.memory_mb is not None else int(total_mem * (part_config.capacity / 100.0))
                cores = part_config.vcores if part_config.vcores is not None else int(total_cores * (part_config.capacity / 100.0))
                max_mem = part_config.max_memory_mb if part_config.max_memory_mb is not None else int(total_mem * (part_config.max_capacity / 100.0))
                max_cores = part_config.max_vcores if part_config.max_vcores is not None else int(total_cores * (part_config.max_capacity / 100.0))
                cap_str = f"[memory={mem},vcores={cores}]"
                max_cap_str = f"[memory={max_mem},vcores={max_cores}]"
            else:
                cap_str = f"{part_config.capacity}"
                max_cap_str = f"{part_config.max_capacity}"

            if part_name == "DEFAULT" or part_name == cluster.default_partition:
                # Default partition
                add_prop(f"{prop_prefix}.capacity", cap_str)
                add_prop(f"{prop_prefix}.maximum-capacity", max_cap_str)
            else:
                # Named partition (Node Label)
                label_prefix = f"{prop_prefix}.accessible-node-labels.{part_name}"
                add_prop(f"{label_prefix}.capacity", cap_str)
                add_prop(f"{label_prefix}.maximum-capacity", max_cap_str)

        # State
        add_prop(f"{prop_prefix}.state", q.state.value)

    # Генерируем XML строку
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>',
        '',
        '<!--',
        f'  Generated by YARN Queue Explorer',
        f'  Cluster: {cluster.name} ({cluster.id})',
        f'  Generated at: {now}',
        f'  Generated by: {generated_by}',
    ]
    if comment:
        lines.append(f'  Comment: {comment}')
    lines.extend([
        '-->',
        '',
        '<configuration>',
    ])

    for name, value, description in properties:
        lines.append('')
        lines.append('  <property>')
        lines.append(f'    <name>{escape(name)}</name>')
        lines.append(f'    <value>{escape(str(value))}</value>')
        if description:
            lines.append(f'    <description>{escape(description)}</description>')
        lines.append('  </property>')

    lines.extend([
        '',
        '</configuration>',
        '',
    ])

    return '\n'.join(lines)
